### ISSUE TITLE
Error when running jekyll --serve

### ISSUE THREAD

**Issue by lsolesen** [jsturtevant/jekyll-vagrant#5]
```
vagrant@precise64:/vagrant/skinny-bones-jekyll$ jekyll --serve                
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

**Comment by lsolesen** [comment]
Trying to run this project: https://github.com/discimport/skinny-bones-jekyll

**Comment by jsturtevant** [comment]
I have not maintained this project as I switched to using docker to serve the project.  It looks like the gem files might not all be up to date.  Could play around with versions....  If you figure it out would appreciate a PR.

You could also check out this post on how to run it locally using:  http://www.jamessturtevant.com/posts/Running-Jekyll-in-Windows-using-Docker/

I am going to update blog post and the ReadMe to point out the new way to run docker.
